test fix ci

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -50,91 +50,91 @@ jobs:
           fi
 
   # build and test the standalone CI
-  build:
-    runs-on: ubuntu-latest
-    needs: [check_draft]
-    strategy:
-      fail-fast: false
-      max-parallel: 3
-      matrix:
-        python-version: ["3.10","3.11","3.12"]
-        package-name:
-          - geos-ats
-          - geos-utils
-          - geos-geomechanics
-          - geos-mesh
-          - geos-processing
-          - geos-timehistory
-          - geos-trame
-          - geos-xml-tools
-          - geos-xml-viewer
-          - mesh-doctor
-          - hdf5-wrapper
-          - pygeos-tools
-        include:
-          - package-name: geos-geomechanics
-            dependencies: "geos-utils"
-          - package-name: geos-mesh
-            dependencies: "geos-utils geos-geomechanics"
-          - package-name: geos-processing
-            dependencies: "geos-utils geos-mesh geos-geomechanics"
-          - package-name: mesh-doctor
-            dependencies: "geos-utils geos-mesh"
-          - package-name: pygeos-tools
-            dependencies: "geos-utils geos-mesh"
-          - package-name: geos-timehistory
-            dependencies: "hdf5-wrapper"
-    steps:
-    - uses: actions/checkout@v4
-    - uses: mpi4py/setup-mpi@v1
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v5
-      with:
-        python-version: ${{ matrix.python-version }}
-        cache: 'pip'
+  # build:
+  #   runs-on: ubuntu-latest
+  #   needs: [check_draft]
+  #   strategy:
+  #     fail-fast: false
+  #     max-parallel: 3
+  #     matrix:
+  #       python-version: ["3.10","3.11","3.12"]
+  #       package-name:
+  #         - geos-ats
+  #         - geos-utils
+  #         - geos-geomechanics
+  #         - geos-mesh
+  #         - geos-processing
+  #         - geos-timehistory
+  #         - geos-trame
+  #         - geos-xml-tools
+  #         - geos-xml-viewer
+  #         - mesh-doctor
+  #         - hdf5-wrapper
+  #         - pygeos-tools
+  #       include:
+  #         - package-name: geos-geomechanics
+  #           dependencies: "geos-utils"
+  #         - package-name: geos-mesh
+  #           dependencies: "geos-utils geos-geomechanics"
+  #         - package-name: geos-processing
+  #           dependencies: "geos-utils geos-mesh geos-geomechanics"
+  #         - package-name: mesh-doctor
+  #           dependencies: "geos-utils geos-mesh"
+  #         - package-name: pygeos-tools
+  #           dependencies: "geos-utils geos-mesh"
+  #         - package-name: geos-timehistory
+  #           dependencies: "hdf5-wrapper"
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - uses: mpi4py/setup-mpi@v1
+  #   - name: Set up Python ${{ matrix.python-version }}
+  #     uses: actions/setup-python@v5
+  #     with:
+  #       python-version: ${{ matrix.python-version }}
+  #       cache: 'pip'
 
-    - name: Install OSMesa and GL
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y libosmesa6
-        sudo apt-get install -y \
-            libegl1-mesa-dev \
-            libgles2-mesa-dev \
-            libgl1-mesa-dev \
-            libx11-dev \
-            libxext-dev
+  #   - name: Install OSMesa and GL
+  #     run: |
+  #       sudo apt-get update
+  #       sudo apt-get install -y libosmesa6
+  #       sudo apt-get install -y \
+  #           libegl1-mesa-dev \
+  #           libgles2-mesa-dev \
+  #           libgl1-mesa-dev \
+  #           libx11-dev \
+  #           libxext-dev
 
-    - name: Install package
-      # working-directory: ./${{ matrix.package-name }}
-      run: |
-        python -m pip install --upgrade pip
+  #   - name: Install package
+  #     # working-directory: ./${{ matrix.package-name }}
+  #     run: |
+  #       python -m pip install --upgrade pip
 
 
-        DEPS="${{ matrix.dependencies || '' }}"
+  #       DEPS="${{ matrix.dependencies || '' }}"
 
-        if [ -n "$DEPS" ]; then
-        echo "Installing additional dependencies: $DEPS"
-        for dep in $DEPS; do
-          python -m pip install ./$dep
-        done
-        fi
+  #       if [ -n "$DEPS" ]; then
+  #       echo "Installing additional dependencies: $DEPS"
+  #       for dep in $DEPS; do
+  #         python -m pip install ./$dep
+  #       done
+  #       fi
 
-        echo "Installing main package..."
-        python -m pip install ./${{ matrix.package-name }}/[test]
-        # LWS Install setuptools first to provide pkg_resources for older plugins
-        python -m pip install setuptools
-        python -m pip install "pytest>=8.0.0" yapf toml "pytest-html>=4.0.0"
+  #       echo "Installing main package..."
+  #       python -m pip install ./${{ matrix.package-name }}/[test]
+  #       # LWS Install setuptools first to provide pkg_resources for older plugins
+  #       python -m pip install setuptools
+  #       python -m pip install "pytest>=8.0.0" yapf toml "pytest-html>=4.0.0"
         
-    - name: Lint with yapf
-      # working-directory: ./${{ matrix.package-name }}
-      run: |
-        yapf -r --diff ./${{ matrix.package-name }} --style .style.yapf
-    - name: Test with pytest
-      #working-directory: ./${{ matrix.package-name }}
-      run:
-      # python -m pytest ./${{ matrix.package-name }} --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html |
-      # wrap pytest to avoid error when no tests in the package
-        sh -c 'python -m pytest ./${{ matrix.package-name }}; ret=$?; [ $ret = 5 ] && exit 0 || exit $ret'
+  #   - name: Lint with yapf
+  #     # working-directory: ./${{ matrix.package-name }}
+  #     run: |
+  #       yapf -r --diff ./${{ matrix.package-name }} --style .style.yapf
+  #   - name: Test with pytest
+  #     #working-directory: ./${{ matrix.package-name }}
+  #     run:
+  #     # python -m pytest ./${{ matrix.package-name }} --doctest-modules --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html |
+  #     # wrap pytest to avoid error when no tests in the package
+  #       sh -c 'python -m pytest ./${{ matrix.package-name }}; ret=$?; [ $ret = 5 ] && exit 0 || exit $ret'
 
   # check if GEOS has label for testing GEOS integration
   check_integration_label:
